### ISSUE TITLE
A response is not always expected when sending a packet

### ISSUE THREAD

**Issue by omelia-iliffe** [robohouse-delft/dynamixel2-rs#9]
Sorry for another issue. Just want to say I am loving using this crate and appreciate all your work! I've learnt loads from it.

Currently, most functions (`bus.write`, `bus.read`) expect a response but a response is not always given.

|                                | `bus.write` | `bus.read` |
| ---------------------------------- | ----------- | ---------- |  
| `id: BROADCAST`                  | no           | no          |        
| `status return level` register = 2 | yes       | yes      |       
| `status return level` register = 1 | no           | yes      |        
| `status return level` register = 0 | no           | no          |        

I'm encountering this issue mostly when sending packets with id: [`packet_id::BROADCAST`](https://github.com/omelia-wetaworkshop/dynamixel2-rs/blob/730ffd160f8f7fddc3017db8ac3ae7273e57f127/src/instructions/mod.rs#L25)

My current work around is to use `bus.write_instruction` when I know a response won't be returned, but this is a bit low level.

A few options:
- We add functions that don't expect responses, like `write_no_response`, but thats a lot more functions if we do it for every write and read fn. We could just to do it the two main ones `write` and `read`
- We add a parameter to the functions, probably something like `response: bool`

What do you think?

**Comment by de-vri-es** [comment]
> Sorry for another issue. Just want to say I am loving using this crate and appreciate all your work! I've learnt loads from it.

No problem. I'm always happy with feedback and real world testing. So thank you for that! I don't always have Dynamixels on hand to test with.

And I'm glad to hear you're happy with the crate so far :D 

> I'm encountering this issue mostly when sending packets with id: [`packet_id::BROADCAST`](https://github.com/omelia-wetaworkshop/dynamixel2-rs/blob/730ffd160f8f7fddc3017db8ac3ae7273e57f127/src/instructions/mod.rs#L25)

Right. I imagine this is a write instruction that you're broadcasting? Because a read instruction wouldn't make much sense without a reply :p

Since the utility of this is (I think) limited to instructions that don't return any data, I think it is a good idea to just change the behavior of those functions not to wait for a response when using the broadcast ID.

They do however return a `Response<()>` now. But I think that isn't a problem. We can just change `transfer_single()` to check for the broadcast ID and return a fake `StatusPacket` with motor ID set to the broadcast ID and alert set to false.

These have special handling already:
* [Ping](https://emanual.robotis.com/docs/en/dxl/protocol2/#ping-0x01): need to use [`scan()`](https://docs.rs/dynamixel2/latest/dynamixel2/struct.Bus.html#method.scan)
* [Sync Read](https://emanual.robotis.com/docs/en/dxl/protocol2/#sync-read-0x82): always uses broadcast ID
* [Bulk Read](https://emanual.robotis.com/docs/en/dxl/protocol2/#bulk-read-0x92): always uses broadcast ID
* [Sync Write](https://emanual.robotis.com/docs/en/dxl/protocol2/#sync-write-0x83)
* [Bulk Write](https://emanual.robotis.com/docs/en/dxl/protocol2/#bulk-write-0x93)
* [Action](https://emanual.robotis.com/docs/en/dxl/protocol2/#action-0x05): need to use [`broadcast_action()`](https://docs.rs/dynamixel2/latest/dynamixel2/struct.Bus.html#method.broadcast_action)

These are not implemented at all yet:
* [Fast Sync Read](https://emanual.robotis.com/docs/en/dxl/protocol2/#fast-sync-read-0x8a)
* [Fast Bulk Read](https://emanual.robotis.com/docs/en/dxl/protocol2/#fast-bulk-read-0x9a)
* [Clear](https://emanual.robotis.com/docs/en/dxl/protocol2/#clear-0x10)
* [Control Table Backup](https://emanual.robotis.com/docs/en/dxl/protocol2/#control-table-backup-0x20)

With these it doesn't make sense to ignore replies so we could just return an error directly without even sending the instruction:
* [Read](https://emanual.robotis.com/docs/en/dxl/protocol2/#read-0x02)

These need to be updated:
* [Write](https://emanual.robotis.com/docs/en/dxl/protocol2/#write-0x03)
* [Reg Write](https://emanual.robotis.com/docs/en/dxl/protocol2/#reg-write-0x04)
* [Action](https://emanual.robotis.com/docs/en/dxl/protocol2/#action-0x05): need to use [`broadcast_action()`](https://docs.rs/dynamixel2/latest/dynamixel2/struct.Bus.html#method.broadcast_action)
* [Factory Reset](https://emanual.robotis.com/docs/en/dxl/protocol2/#factory-reset-0x06): could be dangerous to broadcast when also resetting the motor ID
* [Reboot](https://emanual.robotis.com/docs/en/dxl/protocol2/#reboot-0x08)

Note that I listed `action` twice: there is already `broadcast_action()`, and I think we should keep that function. It's easier to use than filling in the broadcast ID manually, and a pretty normal use case for the `action` instruction. Nevertheless, if we update other instructions to accept the broadcast ID, I think that `action()` should also be updated to allow it.

-----

So, lots of text but in the end I think this can be a pretty straightforward change.

Would you like to do it or shall I?

**Comment by omelia-iliffe** [comment]
I'm not sure changing it for just the broadcast id resolves the problem in all cases.
There are some non broadcast use cases where no response can be expected from the `write` and `read` funcs:  
As I mentioned, you can configure the [`status-return-level` register](https://emanual.robotis.com/docs/en/dxl/x/xm540-w270/#status-return-level) to only return on read instructions or never return a response at all. 
Sure, calling `read` and not expecting a reply is pretty silly. I didn't think about that when writing it up lol.
But calling write without a response (and not to the broadcast id) can have speed benefits.

My use case is the broadcast id, so maybe resolving that and flagging the other as an issue for later would be acceptable.  
I'm a little under the pump at the moment. I'd be very grateful if you could implement the changes :)

**Comment by de-vri-es** [comment]
Oh, sorry, I missed the bit about the `status return level`. I think that's a valid concern that may require a different design. What I said above indeed only applies to broadcast messages.

It's a bit annoying to deal with the status return level correctly, since it's a per-device setting. Additionally, the control table layout is not something we can really rely on, since even that is device specific. This crate just implements the protocol, it doesn't have any device specific knowledge.

So I don't think it's acceptable for this library to do something like set or query the status return level register automatically.

I would also prefer not to add a boolean argument to all instructions though. And I would like to avoid duplicating all functions (as you said, there's already quite a lot).

There are three options that I see:
1. Add a [`Bus`](https://docs.rs/dynamixel2/latest/dynamixel2/struct.Bus.html)-level configuration flag to not expect status packets on write command.

   This doesn't match perfectly with reality, since it assumes the same setting for all motors on the bus. However, when broadcasting there is no reply anyway. And if you really need to, you can enable/disable expecting status packets just before sending your instruction.

2. Return a fancy object from each command that still has a function to either `wait()` for a response or `ignore()` any possible response.

   It would be easy to accidentally ignore the returned object, but this can be solved by adding a `#[must_use]` annotation. This relies on users properly processing warnings though. Especially during fast development cycles, some people temporarily have so many warnings that they don't read them all.

   Another downside is that as a user, you will now need to deal with the send and read error are reported separately and must be handled separately. Unless we even defer the write until `wait()` or `ignore()` is called.

   But the biggest downside in my mind is that it just feels complicated. As a user I would just expect all the work to be done by one function. Documenting such an object that represents a deferred action in an easy-to-understand way feels like a challenge.

3. Ignore the status return level for now, in the hopes that some good solution presents itself later.

   This is probably wishful thinking though.
   
Considering the three options, I feel like 1 is the most pragmatic, although not the most beautiful. So I'm leaning towards that one. But I will probably start with only handling the broadcast ID and leave the status return level for a separate PR.

> I'm a little under the pump at the moment. I'd be very grateful if you could implement the changes :)

Alright! No worries.

**Comment by de-vri-es** [comment]
First version dealing with the broadcast ID should be implemented in #10. Would be super useful if you can test it, since I don't have a dynamixel right now.

But if not, no worry, maybe I can find one.

**Comment by omelia-iliffe** [comment]
Fixed with pr #10 and release `v0.8.0` :rocket:
